version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - ./db-data:/var/lib/mysql

  webserver:
    image: httpd:latest  # Use the official Apache2 image from Docker Hub
    ports:
      - "8080:80"
    volumes:
      - ./apache-config:/etc/apache2/sites-enabled
      - ./apache-config:/usr/local/apache2/conf/sites-enabled  # Adjust the path as needed
